### ISSUE TITLE
@param ...

### ISSUE THREAD

**Issue by pet221** [michaeldumelle/SSN2temp2#7]
Do you  include this extra parameter in every function that's exported? If not, which ones should I include it in? I noticed it's in varcomp, but not Torgegram (which I now see is included in SSN2). 

#' @param ... Other arguments. Not used (needed for generic consistency).

**Comment by michaeldumelle** [comment]
`...` is only needed when it is a function argument. By R rules, `...` must be included in any generic methods we export (see [Section 7 here](https://cran.r-project.org/doc/manuals/R-exts.html#Generic-functions-and-methods). So it is in every generic (even if no arguments can be passed within it). It is also used when we allow users to "pass" arguments to other functions -- for example, `ssn_lm()` / `ssn_glm()` use `...` because the user can pass arguments to `optim()`. But it is not in `Torgegram()` (currently) because `Torgegram()` is not a generic and no additional arguments are passed to any function calls within `Torgegram()`.
