### ISSUE TITLE
predict versus predict.ssn_lm

### ISSUE THREAD

**Issue by pet221** [michaeldumelle/SSN2temp2#9]
Are we supposed to have two prediction functions in predict.R and predict_glmR? I'm asking because predict.ssn_lm (in predict.R) makes a covariance object, does block prediction, and the helpfile says it works with fitted models from ssn_glm() as well as ssn_lm(). The predict.ssn_glm() in predict_glm.R isn't as well documented - is this a legacy file from an earlier version?

**Comment by michaeldumelle** [comment]
They roxygen comments document them together, so the predict_glm.R documentation only contains stuff not in the predict_lm.R documentation. Notice that running ?predict.ssn_lm, ?predict.ssn_glm, or ?predict.ssn points you towards documentation for both predict.ssn_lm and predict.ssn_glm. There are a few documentation updates that need to take place here because some spmodel language is used, but that will all get fixed when I revisit documentation prior to release.
